# These are supported funding model platforms

github: [petterjuan]  # Your GitHub username for sponsorships
custom: 
  - "https://github.com/petterjuan/agentic-reliability-enterprise"  # Enterprise edition
  - "https://arf.dev/enterprise"  # Enterprise website coming soon
  - "mailto:petter2025us@outlook.com"  # Contact for commercial inquiries
  - "https://www.linkedin.com/in/petterjuan"  # Professional contact
